apiVersion: "v1"
kind: "Service"
metadata:
  name: "react-docker-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "react-docker"
  type: "LoadBalancer"
  loadBalancerIP: ""
