# Generated by Django 4.1.3 on 2022-11-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(max_length=4, verbose_name='Symbol')),
                ('value', models.DecimalField(decimal_places=20, max_digits=40, verbose_name='Value')),
                ('createdDate', models.DateTimeField(auto_now=True, verbose_name='CreatedDate')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, verbose_name='FirstName')),
                ('lastName', models.CharField(max_length=30, verbose_name='LastName')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
            ],
        ),
    ]
