# Generated by Django 4.1.3 on 2022-11-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeform',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscribeform',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Email'),
        ),
    ]
